11704 break up large geo requests to build map view in 500 increments
NYCPlanning/labs-factfinder pull request #1073
Opened 2023-02-10 18:52 UTC by horatiorosa

### Summary
First hack at this bug:
 Selecting large amounts of census tracks or blocks causes the api to return a `ERR_FAILED 414 (Request-URI Too Long)` error. 

One pass at the solution is to break up the request is to somewhat smaller chucks and build up to accumulate the final results needed. THe solution works but the response time can range from 1 to 1.5 seconds.

#### Tasks/Bug Numbers
 - Fixes [AB#11704](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/11704)

2023-02-27 16:13 UTC, TangoYankee commented on app/utils/fetch-selection-summary.js
> +  // to ensure we don't receive errors from the URLs being too long, we limit the selections to 1500 geoids
should `1500` read `1000`?

2023-03-15 14:53 UTC, TylerMatteo requested changes

2023-03-15 15:08 UTC, horatiorosa commented on app/styles/modules/_m-colors.scss
> +;
oops! will rename and remove xtra `;`

2023-03-15 15:11 UTC, horatiorosa commented on app/templates/components/map-utility-box.hbs
> +            <svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
No, these are icons from Chakra that Design requested to be used.

2023-03-15 17:46 UTC, horatiorosa commented on app/utils/fetch-selection-summary.js
> +  // to ensure we don't receive errors from the URLs being too long, we limit the selections to 1500 geoids
500, hehe

2023-03-15 17:46 UTC, horatiorosa commented on app/templates/map-to-explorer.hbs
> +  {{/if}}
gone gone gone

2023-03-15 17:47 UTC, TangoYankee commented on app/utils/fetch-selection-summary.js
> +  // to ensure we don't receive errors from the URLs being too long, we limit the selections to 1500 geoids
I can't keep up!

2023-03-15 20:29 UTC, TangoYankee requested changes
I'm able to get the user feedback message when breaking an existing selection into smaller geography. However, I can't get the message to appear when starting a fresh selection with the polygon or radius selectors.

2023-03-15 21:19 UTC, horatiorosa commented on app/utils/fetch-selection-summary.js
> +    selectionResponse = null;
@TylerMatteo 
Using the POLYGON and RADIUS  and exceeding the max getoid selection limit will not generate the map-utility-box template (displaying the selection count, error message and the clear selection link) without returning `selectionResponse = null` here.

This explains why I never encountered the issue that Tim discovered until after this change. 100 internets to  @TangoYankee  for finding this bug in the big fix.

2023-03-16 00:13 UTC, closed without merging